# Check if the file exists before sourcing it
settings_file="$(dirname "$0")/settings/temp.sh"
if [ -f "$settings_file" ]; then
    echo "" # pass the file exists
else
    read -p "Enter the reload command:(e.g \"php -S localhost:8080\") " user_command
    read -p "Enter port used:(e.g \"8080\") " port_no
    {
        echo "#!/bin/bash"
        echo "# This file contains the reload command for the monitoring script"
        echo "# Do not manually edit this file. It is generated by the script."
        echo ""
        echo "reload=\"$user_command &\""
        echo "port_number=\"$port_no\""

    } > "$(dirname "$0")/settings/temp.sh"
        
fi
